version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "5000:5000"
    volumes:
      - ../audiobooks:/app/audiobooks
    environment:
      - FLASK_ENV=production
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped