version: '3.8'

services:
  bilipala-downloader:
    image: nbzzd6/bilipala-downloader:latest
    ports:
      - "5000:5000"
    volumes:
      - ./audiobooks:/app/Audiobooks
      - ./tasks:/app/download_tasks
      - ./history:/app/download_history
      - ./config:/app/config
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
