version: '3.8'

services:
  bili-audio-downloader:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./audiobooks:/app/audiobooks
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
