name: Monitor yt-dlp Updates

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

permissions:
  actions: write
  repository-projects: write
  
jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest yt-dlp version
        id: ytdlp
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest | jq -r .tag_name)
          echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          CURRENT_VERSION=$(grep yt-dlp requirements.txt | cut -d'>' -f2)
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Trigger Docker build workflow
        if: steps.ytdlp.outputs.latest_version != steps.ytdlp.outputs.current_version
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: update-yt-dlp
          client-payload: '{"version": "${{ steps.ytdlp.outputs.latest_version }}"}'
